/* eslint-disable no-unused-vars */
const exbrowser = "edge";
// values: "chrome", "safari", "edge", "firefox", "opera", "yandex", "whale"
const linkredirectionoptions = "https://www.turnoffthelights.com/browser/extension/options/";
const linkcapturescreenshot = "https://www.turnoffthelights.com/browser/extension/capture-screenshot-of-video/";
const linkdeveloperwebsite = "https://www.turnoffthelights.com";
const linkproduct = "https://microsoftedge.microsoft.com/addons/detail/turn-off-the-lights/fmamkbgpnienhphflfdamlhnljffjdgm";
const linkdonate = "https://www.turnoffthelights.com/donate/";
const writereview = "https://microsoftedge.microsoft.com/addons/detail/turn-off-the-lights/fmamkbgpnienhphflfdamlhnljffjdgm";
const linkchangelog = "https://www.turnoffthelights.com/browser/extension/changelog/edge/";
const linktranslate = "https://www.turnoffthelights.com/browser/extension/translate/";
const linksupport = "https://www.turnoffthelights.com/support/";
const linkwelcome = "https://www.turnoffthelights.com/browser/extension/welcome/edge/";
const linkuninstall = "https://www.turnoffthelights.com/browser/extension/uninstall/edge/";
const linkguide = "https://www.turnoffthelights.com/browser/extension/guide/edge/";
const linkbrowsertheme = "https://www.turnoffthelights.com/browser/theme/";
const browsernewtab = "edge://newtab/";
const browserstore = "https://microsoftedge.microsoft.com";
const linkyoutube = "https://www.youtube.com/@turnoffthelights?sub_confirmation=1";
const linkauroraplayerapp = "https://www.stefanvd.net/project/aurora-player/";
const linktotlmobileapp = "https://www.turnoffthelights.com/mobile/";
const linkgamepad = "https://www.turnoffthelights.com/game-controller/";
const devmode = true;
const devdonate = false;